miniBlog/blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns = [
    path('register/',views.register.as_view(),name="register"),
    path('login/',views.loginPage.as_view(),name="login"),
    path('listPost/',views.listPost.as_view(),name="listPost"),
    path('editPost/',views.editPost.as_view(),name="editPost"),
    path("deletePost/<int:pk>/",views.deletePost.as_view(),name="deletePost"),
    path('postDetail/<int:pk>/',views.postDetail.as_view(),name="postDetail"),
    path('editComment/<int:npost>/',views.editComment.as_view(),name="editComment"),
    path('deleteComment/<int:pk>/',views.deleteComment.as_view(),name="deleteComment"),
    path('logout/',views.lgoutView.as_view(),name="logout"),
    path('',views.loginPage.as_view(),name="root")
]

miniBlog/miniBlog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

miniBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class userDetail(models.Model):
    user = models.OneToOneField(to=User,on_delete=models.CASCADE,)
    hobby = models.CharField(max_length=30)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=False,blank=False,max_length=20)
    text = models.TextField(null=False,blank=False,max_length=2000)
    def __str__(self):
        return self.title
    def last_comment(self):
        try:
            return self.comment_set.all().order_by('-id')[0]
        except IndexError:
            pass
    
class Comment(models.Model):
    Post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(null=False,blank=False,max_length=1000)

miniBlog/blog/forms.py
from django.forms import ModelForm,PasswordInput,CharField,Form
from .models import userDetail,Post,Comment
from django.contrib.auth.models import User
from django.core.validators  import RegexValidator

class RegisterUserForm(ModelForm):
    class Meta:
        model = userDetail
        fields = ['hobby']


class CustopmloginForm(Form):
    username=CharField(label='Your username', max_length=100,validators=[RegexValidator(regex="^[A-Za-z1-9_-]*$"
    ,message="Username invalid : must not contain spection charcters"),])
    password=CharField(widget=PasswordInput(),label='Your password', max_length=100)

class EditPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title","text"]
        labels = {
            'title': 'Title :',
            'text': 'Please enter your post text :',
        }

class EditCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        labels = {
            'text': 'Please type your comment :',
        }

miniBlog/blog/views.py
from django.shortcuts import render,redirect,reverse
from django.views.generic import TemplateView,FormView,ListView,DetailView,DeleteView
from django.views import View
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm,CustopmloginForm,EditPostForm,EditCommentForm
from django.contrib.auth import authenticate, login , logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post,Comment
from django.urls import reverse_lazy
from django.contrib.auth.models import User

# Create your views here.
#logout(request)

class lgoutView(View):
    def get(self, request):
        if (request.method=="GET"):
            logout(request)
            return redirect("blog:login")

class register(View):
    template_name = "blog/register.html"

    def get(self, request):
        if (self.request.user.is_authenticated ):
            return redirect("blog:listPost")
        if (request.method=="GET"):
            return render(request,"blog/register.html",context={"UserForm": UserCreationForm() 
            , "UserDetail": RegisterUserForm()})

    def post(self, request):
        result=None
        if (request.method=="POST"):
            _user=UserCreationForm(request.POST)
            _userDetail=RegisterUserForm(request.POST)

            if (_user.is_valid() and _userDetail.is_valid() ):
                user=_user.save()
                userD=_userDetail.save(commit=False)
                userD.user=user
                userD.save()
                result="User created succesfully"
        return render(request,"blog/register.html",context={"UserForm": _user 
            , "UserDetail": _userDetail , "result": result })
    
class loginPage(FormView):
    template_name = 'blog/login.html'
    form_class = CustopmloginForm
    success_url = '/listPost'
    result=None

    def get(self, request):
        if (self.request.user.is_authenticated ):
            return redirect("blog:listPost")
        return super().get(request)
        #return self.render_to_response(self.get_context_data())

    def form_valid(self, form):
        user=form
        if (self.request.user.is_authenticated ):
            return redirect("blog:listPost")
        if (self.request.method=="POST"):
            if (user.is_valid()):
                username=user.cleaned_data["username"]
                password=user.cleaned_data["password"]
                user = authenticate(self.request, username=username, password=password)
                if user is not None:
                    login(self.request, user)
                    self.result="Auth succesfull"
                    return super().form_valid(form)
                else:
                    self.result="Login failed"
                    return super().form_invalid(form)


    def get_context_data(self,**kwargs):
        super()
        if 'result' not in kwargs:
            kwargs['result'] = self.result
        return super().get_context_data(**kwargs)

class editPost(LoginRequiredMixin,FormView):
    template_name = 'blog/editPost.html'
    form_class = EditPostForm
    success_url = '/listPost'
    result=None
    login_url="/login"

    def get(self, request):
        if ( not self.request.user.is_authenticated ):
            return redirect("blog:login")
        return super().get(request)
        #return self.render_to_response(self.get_context_data())

    def form_valid(self, form):
        post=form
        if ( not self.request.user.is_authenticated ):
            return redirect("blog:login")
        if (self.request.method=="POST"):
            if (post.is_valid()):
                _post=post.save(commit=False)
                _post.user=self.request.user
                _post.save()
                return super().form_valid(form)

class listPost(ListView):
    paginate_by = 20
    model = Post
    template_name="blog/listPost.html"
    ordering="-id"

    def get_context_data(self, *, object_list=None, **kwargs):
            context = super().get_context_data(**kwargs)
            context["forward"]=range(context["page_obj"].number+1,context["page_obj"].number+4)
            context["backward"]=range(context["page_obj"].number-4,context["page_obj"].number)
            return context


def postDetailx(request):
    return render(request,'blog/postDetail.html')

class postDetail(DetailView):
    template_name='blog/postDetail.html'
    model = Post
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"]=self.object.comment_set.all()
        for i in context["comments"]:
            print( i.user.id )
        return context



class deletePost(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:listPost')
    template_name="blog/deletePost.html"

    def get(self, request,**kwargs):
        if (self.request.user==self.get_object().user ):
            return super().get(request,**kwargs)
        elif (  self.request.user.is_superuser ) :
            return super().get(request,**kwargs)
        else:
            return redirect(reverse("blog:postDetail",kwargs={"pk":self.get_object().id}))


class editComment(LoginRequiredMixin,FormView):
    template_name="blog/editComment.html"
    form_class=EditCommentForm
    success_url = None
    result=None
    login_url="/login"

    def form_valid(self, form):
        comment=form
        if ( not self.request.user.is_authenticated ):
            return redirect("blog:login")
        if (self.request.method=="POST"):
            if (comment.is_valid()):
                _comment=comment.save(commit=False) 
                _comment.user=self.request.user
                #_post.Post=Post.objects.filter(pk=self.kwargs['post_id']).get()
                post=Post.objects.filter(pk=self.kwargs['npost']).get()
                _comment.Post=post
                print(_comment.user)
                _comment.save()
                self.success_url="/postDetail/"+ str(_comment.Post.id)+"/"
                return super().form_valid(form)

class deleteComment(DeleteView):
    model = Comment
    template_name="blog/deleteComment.html"

    def get(self, request , pk):
        self.object=self.get_object()
        if ( not self.request.user.is_superuser ):
            return redirect("blog:login")
        elif (self.request.user!= self.object.user and ( not self.request.user.is_superuser)):
            return redirect("blog:login")
        return super().get(request)

    def get_success_url(self):
        self.success_url=reverse_lazy("blog:postDetail",kwargs={"pk":self.object.Post.id})
        return super().get_success_url()

miniBlog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>MiniBlog</title>
        {% block css %}
        {% endblock css %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body style="background: #ecf0f1;">
        <!--NavBar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-primary" >
        <a class="navbar-brand text-primary" href="#">MiniBlog </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url "blog:listPost" %}">Articles</a>
            </li>
            </ul>
            <ul class="d-flex justify-content-end   navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text mb-0 mt-2 mr-3">
                 <p  href='#'>{{ user.username }}</p>
                </span>
            </li>
            <li class="nav-item">
                <span class="navbar-text mr-3">
                <a class=" nav-link" href="{% url "blog:logout" %}">Logout</a>
                </span>
            </li>
            {% else %}
            <li class="nav-item">
                <span class="navbar-text mr-3" >
                <a class=" nav-link" href="{% url "blog:login" %}">Login</a>
                </span>
            </li>
            <li class="nav-item">
                <span class="navbar-text mr-3">
                <a class="nav-link" href="{% url "blog:register" %}">Register</a>
                </span>
            </li>
            {% endif %}
            </ul>
        </div>
        </nav>
        <!--NavBar end-->
        <div >
        {% block body %}
        {% endblock body %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% block js %}
        {% endblock js %}       
        </div>
    </body>
</html>

miniBlog/templates/blog/deleteComment.html
{% extends 'blog/base.html' %}
{% load custom_tags %}
{% block body %}
<div class="container pt-3">
    <div class="row">
        <div class="col-3"> </div>
        <div class="col-6 p-1 text-center custom-form form-delete bg-light h-5">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete thi comment ?</p>
                <input class="btn btn-danger"  type="submit" value="Confirm">
            </form>
        </div>
        <div class="col-3"> </div>
    </div>
</div>
{% endblock body %}

miniBlog/templates/blog/deletePost.html
{% extends 'blog/base.html' %}
{% load custom_tags %}
{% block body %}
<div class="container pt-3">
    <div class="row">
        <div class="col-3"> </div>
        <div class="col-6 p-1 text-center custom-form form-delete bg-light h-5">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete this post "{{ object.title }}" ?</p>
                <input class="btn btn-danger"  type="submit" value="Confirm">
            </form>
        </div>
        <div class="col-3"> </div>
    </div>
</div>
{% endblock body %}

miniBlog/templates/blog/editComment.html
{% extends 'blog/base.html' %}
{% load static %}
{% load custom_tags %}
{% block css %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
{% endblock css %}

{% block body %}
<div class="container pt-3">
    <div class="row">
        <div class="col-2 ml-0"> </div>
        <div class="col-8 custom-post bg-light h-5">
            <p class="custom-post-title post-list-box text-light bg-dark text-center"> Edit comment </p>
            <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <!-- <textarea class="col-12 editable" cols="1000" rows="100" type="textarea"></textarea>-->
                {{  form.text | add_class:"col-12 editable" }}
                <div class=" m-0  p-0 d-flex justify-content-center row">
                    <button type="submit" class="btn btn-primary">Submit comment</button>
                </div>
            </div>
        </div>
        <div class="col-2 mr-0"> </div>
    </div>
</div>
{% endblock body %}


{% block js %}
<script src="{% static 'js/medium-editor.min.js' %}"></script>
<script src="{% static 'js/edit.js' %}" ></script>
{% endblock js %}

miniBlog/templates/blog/editPost-raw.html
{% extends 'blog/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
{% endblock css %}

{% block body %}
<div class="container pt-3">
    <div class="row">
        <div class="col-2 ml-0"> </div>
        <div class="col-8 custom-post bg-light h-5">
            <p class="custom-post-title post-list-box text-light bg-dark text-center"> Edit Post </p>
            <form>
            <div class="form-group">
                <label class="ml-2" >Email address</label>
                <input type="text" class="form-control" placeholder="Enter post title">
                <label class="ml-2" >Write post details</label>
                <textarea class="col-12 editable" cols="1000" rows="100" type="textarea"></textarea>
                <div class=" m-0  p-0 d-flex justify-content-center row">
                    <button type="button" class="btn btn-primary">Submit post</button>
                </div>
            </div>
        </div>
        <div class="col-2 mr-0"> </div>
    </div>
</div>
{% endblock body %}


{% block js %}
<script src="{% static 'js/medium-editor.min.js' %}"></script>
<script src="{% static 'js/edit.js' %}" ></script>
{% endblock js %}

miniBlog/templates/blog/editPost.html
{% extends 'blog/base.html' %}
{% load static %}
{% load custom_tags %}

{% block css %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
{% endblock css %}

{% block body %}
<div class="container pt-3">
    <div class="row">
        <div class="col-2 ml-0"> </div>
        <div class="col-8 custom-post bg-light h-5">
            <p class="custom-post-title post-list-box text-light bg-dark text-center"> Edit Post </p>
            <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="ml-2" >{{ form.title.label }}</label>
                {{ form.title | add_class:"form-control" }}
                <label class="ml-2" >{{ form.text.label }}</label>
                {{ form.text | add_class:"col-12 editable " }}
                <div>
                    {{ form.title.errors }}
                    {{ form.text.errors }}
                    {{ form.errors }}
                </div>
                <div class=" m-0  p-0 d-flex justify-content-center row">
                    <button type="submit" class="btn btn-primary">Submit post</button>
                </div>
            </div>
        </div>
        <div class="col-2 mr-0"> </div>
    </div>
</div>
{% endblock body %}


{% block js %}
<script src="{% static 'js/medium-editor.min.js' %}"></script>
<script src="{% static 'js/edit.js' %}" ></script>
{% endblock js %}

miniBlog/templates/blog/listPost-raw.html
{% extends 'blog/base.html' %}
{% block body %}
<div class="container pt-3">
    <div class="row">
    <div class="col-1 ml-0"> </div>
    <div class="col-9 custom-post bg-light h-5">

        <p class="custom-post-title post-list-box text-light bg-dark text-center"> Post list </p>
        {% if user.is_authenticated %}
        <div class="post-border  ">
                <div class='container post-list-container  d-flex justify-content-center'>
                        <table class="post-list col-12">
                            <thead class="post-head" >
                                <tr>
                                    <th> Post name </th>
                                    <th> Post detail </th>
                                    <th> Last comment </th>
                                    <th> Author </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td> Post 1  </td>
                                    <td> detail 1 </td>
                                    <td> Last comment by mouslih </td>
                                    <td> Mehdi1  </td>
                                </tr>
                                <tr>
                                    <td> Post 2  </td>
                                    <td> detail 2 </td>
                                    <td> Last comment by mahdi </td>
                                    <td> mehdi2 </td>
                                </tr>
                                <tr>
                                    <td> Post 2  </td>
                                    <td> detail 2 </td>
                                    <td> Last comment by mahdi </td>
                                    <td> mehdi2 </td>
                                </tr>
                                <tr>
                                    <td> Post 2  </td>
                                    <td> detail 2 </td>
                                    <td> Last comment by mahdi </td>
                                    <td> mehdi2 </td>
                                </tr>
                                <tr>
                                    <td> Post 2  </td>
                                    <td> detail 2 </td>
                                    <td> Last comment by mahdi </td>
                                    <td> mehdi2 </td>
                                </tr>
                                <tr>
                                    <td> Post 2  </td>
                                    <td> detail 2 </td>
                                    <td> Last comment by mahdi </td>
                                    <td> mehdi2 </td>
                                </tr>
                                <tr>
                                    <td> Post 2  </td>
                                    <td> detail 2 </td>
                                    <td> Last comment by mahdi </td>
                                    <td> mehdi2 </td>
                                </tr>                                
                            </tbody>
                        </table>
            </div>
                    <!-- Pagination -->
            <div class=" d-flex justify-content-center">
                <nav  aria-label=" ...">
                <ul class="pagination">
                    <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active">
                    <span class="page-link">
                        2
                        <span class="sr-only">(current)</span>
                    </span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
                </nav>
            </div>
        </div>
        <div class="col-1 mr-0"> </div>
        </div>

</div>
{% endblock body %}

miniBlog/templates/blog/listPost.html
{% extends 'blog/base.html' %}
{% block body %}
<div class="container pt-3">
    <div class="row">
    <div class="col-1 ml-0"> </div>
    <div class="col-9 custom-post bg-light h-5">

        <p class="custom-post-title post-list-box text-light bg-dark text-center"> Post list </p>
        {% if user.is_authenticated %}
        <div class="custom-post-add">
            <a  href="{% url "blog:editPost" %}" class="  text-dark bg-light text-center"> Add Post </a>  
        </div>
        {% endif %}

        <div class="post-border  ">
                <div class='container post-list-container  d-flex justify-content-center'>
                        <table class="post-list col-12">
                            <thead class="post-head" >
                                <tr>
                                    <th> Post name </th>
                                    <th> Post detail </th>
                                    <th> Last comment </th>
                                    <th> Author </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post in page_obj %}
                                <tr>
                                    <td> <a href="{% url "blog:postDetail" post.id %}"> {{ post.title | truncatechars:20 }} </a> <br> </td>
                                    <td> {{ post.text  | truncatechars:9 | safe }} </td>
                                    <td>  {{  post.last_comment.user.username  }} </td>
                                    <td> {{ post.user.username }} </td>
                                </tr> 
                                {% endfor %}                           
                            </tbody>
                        </table>
            </div>
                    <!-- Pagination -->
            <div class=" d-flex justify-content-center">
                <nav  aria-label=" ...">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                        <li class="page-item disabled">
                            {% if  page_obj.number != 1 %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                            {% endif %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                        </li>
                    {% endif %}
                    {% for i in backward  %}
                        {% if i >= 1 %}
                        <li class="page-item" ><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <li class="page-item active">
                    <span class="page-link">
                        {{ page_obj.number }}
                        <span class="sr-only">{{ page_obj.number }}</span>
                    </span>
                    </li>
                    {% for i in forward  %}
                        {% if i <= paginator.num_pages %}
                        <li class="page-item" ><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    </li>
                    </li>
                    {% if page_obj.has_next %}
                         <li class="page-item" ><a class="page-link"  href="?page={{ page_obj.next_page_number }}">next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
                    {% endif %}
                    </li>
                    
                </ul>
                </nav>
            </div>
        </div>
        <div class="col-1 mr-0"> </div>
        </div>

</div>
{% endblock body %}

miniBlog/templates/blog/login-raw.html
{% extends 'blog/base.html' %}
{% block body %}
<div class="container pt-3">
    <div class="row">
    <div class="col-4"> </div>
    <div class="col-4 custom-form form-login bg-light">
        
        <p class="custom-form-title text-light bg-dark text-center"> Login form </p>
        <!--Register form -->
        <div class="container "> 
            <form>
                <div class="form-group">
                <label class="ml-2" for="email-address">Email address</label>
                <input type="email" class="form-control" id="email-address"  placeholder="Enter your email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                <label class="ml-2" for="password">Password</label>
                <input type="password" class="form-control" id="password" placeholder="Enter your password">
                </div>
                <div class="row  submit-form"> 
                    <div class="col-2"></div>
                    <div class="col-8">
                        <button  type="submit" class="btn btn-primary">login</button>
                    </div>
                    <div class="col-2"></div>
                </div>
            </form>
        </div>
        <!--Register form end-->
    </div>
    <div class="col-4"> </div>
    </div>
</div>
{% endblock body %}

miniBlog/templates/blog/postDetail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
{% endblock css %}

{% block body %}
<div class="container pt-3">
    <div class="row">
        <div class="col-2 ml-0"> </div>
        <div class="col-8 custom-post bg-light h-5">
            <p class="custom-post-title post-list-box text-light bg-dark text-center">  {{ object.title }} </p>
            <form>
            <div class="">
                <div class="col-12 detail_div  col-12 " > {{ object.text | safe }} </div>
                <div class=" m-0  p-0 d-flex justify-content-center row">
                    <a class="col-3"  href="{% url "blog:editComment" object.id %}"><button type="button" class=" btn btn-primary">Add comment</button></a>
                    
                    
                    {% if object.user == user or user.is_superuser %}
                    <a class="col-3"  href="{% url "blog:deletePost" object.id %}"><button type="button" class=" btn btn-danger">Delete </button> </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-2 mr-0"> </div>
    </div>

    {% if comments %}
        <div class="row">
        <div class="col-2 ml-0"></div>
        <div class="col-8 custom-comment bg-light h-5">
            <p class="custom-post-title post-list-box text-light bg-dark text-center"> Comments </p>
            {%  for comment in comments %}
            <div class="comment-container">
            <div class='row'>
                <div class="col-2 text-center"><p> {{ comment.user.username }}  </p></div>
                <div class="col-10" >{{ comment.text | safe }}</div>
            </div>
            {% if comment.user == user or user.is_superuser %}
            <div class="   p-0 d-flex justify-content-end row">
                    <a class="col-3"  href="{% url "blog:deleteComment" comment.id %}"><button type="button" class=" ml-auto btn btn-danger">Delete </button> </a>
            </div>
            {% endif %}
            </div>
            {% endfor %}
       {% endif %}
        <div class="col-2 mr-0"> </div>
    </div>
</div>
{% endblock body %}


{% block js %}
<script src="{% static 'js/medium-editor.min.js' %}"></script>
<script src="{% static 'js/edit.js' %}" ></script>
{% endblock js %}